back/admin/integrations/urls.py
from django.urls import path

from . import views

app_name = "integrations"
urlpatterns = [
    path("slack", views.SlackOAuthView.as_view(), name="slack"),
    path("create", views.IntegrationCreateView.as_view(), name="create"),
    path(
        "delete/<int:pk>/",
        views.IntegrationDeleteView.as_view(),
        name="delete",
    ),
    path("update/<int:pk>/", views.IntegrationUpdateView.as_view(), name="update"),
    path(
        "create/google_login/",
        views.IntegrationCreateGoogleLoginView.as_view(),
        name="create-google",
    ),
    path("oauth/<int:pk>/", views.IntegrationOauthRedirectView.as_view(), name="oauth"),
    path(
        "oauth/<int:pk>/callback/",
        views.IntegrationOauthCallbackView.as_view(),
        name="oauth-callback",
    ),
    path(
        "update_creds/<int:pk>/",
        views.IntegrationUpdateExtraArgsView.as_view(),
        name="update-creds",
    ),
    path(
        "tracker/",
        views.IntegrationTrackerListView.as_view(),
        name="trackers",
    ),
    path(
        "tracker/<int:pk>/",
        views.IntegrationTrackerDetailView.as_view(),
        name="tracker",
    ),
    path(
        "builder/",
        views.IntegrationBuilderView.as_view(),
        name="builder",
    ),
    path(
        "builder/<int:pk>/",
        views.IntegrationBuilderView.as_view(),
        name="builder",
    ),
    path(
        "builder/json/",
        views.IntegrationTestDownloadJSONView.as_view(),
        name="builder-json",
    ),
    path(
        "builder/test/",
        views.IntegrationTestView.as_view(),
        name="builder-test",
    ),
]

back/admin/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"
urlpatterns = [
    path("general/", views.OrganizationGeneralUpdateView.as_view(), name="general"),
    path("slack/", views.SlackSettingsUpdateView.as_view(), name="slack"),
    path(
        "personal/language/",
        views.PersonalLanguageUpdateView.as_view(),
        name="personal-language",
    ),
    path("personal/otp/", views.OTPView.as_view(), name="personal-otp"),
    path(
        "welcome_message/<slug:language>/<int:type>/",
        views.WelcomeMessageUpdateView.as_view(),
        name="welcome-message",
    ),
    path(
        "welcome_message/<slug:language>/<int:type>/test_message/",
        views.WelcomeMessageSendTestMessageView.as_view(),
        name="welcome-message-test-message",
    ),
    path("integrations/", views.IntegrationsListView.as_view(), name="integrations"),
    path(
        "integrations/slack_account/update_channels/",
        views.SlackChannelsUpdateView.as_view(),
        name="slack-account-update-channels",
    ),
    path(
        "integrations/slack_bot/", views.SlackBotSetupView.as_view(), name="slack-bot"
    ),
    path(
        "administrators/", views.AdministratorListView.as_view(), name="administrators"
    ),
    path(
        "administrators/<int:pk>/update/",
        views.AdministratorUpdateView.as_view(),
        name="administrators-update",
    ),
    path(
        "administrators/create/",
        views.AdministratorCreateView.as_view(),
        name="administrators-create",
    ),
    path(
        "administrators/<int:pk>/delete/",
        views.AdministratorDeleteView.as_view(),
        name="administrators-delete",
    ),
]

back/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("employees/", views.EmployeeView.as_view(), name="employees"),
    path("sequences/", views.SequenceView.as_view(), name="sequences"),
]

back/back/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import TemplateView

import user_auth
from admin.admin_tasks import urls as admin_tasks_urls
from admin.appointments import urls as appointment_urls
from admin.badges import urls as badge_urls
from admin.hardware import urls as hardware_urls
from admin.integrations import urls as integrations_urls
from admin.introductions import urls as intro_urls
from admin.people import urls as people_urls
from admin.preboarding import urls as preboarding_urls
from admin.resources import urls as resource_urls
from admin.sequences import urls as sequences_urls
from admin.settings import urls as settings_urls
from admin.templates import urls as template_urls
from admin.to_do import urls as to_do_urls
from api import urls as public_api_urls
from new_hire import urls as new_hire_urls
from organization import urls as org_urls
from organization import views as org_views
from slack_bot import urls as slack_urls
from user_auth import urls as auth_urls

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include(auth_urls)),
    path(
        "api/auth/google_login",
        user_auth.views.GoogleLoginView.as_view(),
        name="google_login",
    ),
    path("api/org/", include(org_urls)),
    path("setup/", org_views.InitialSetupView.as_view(), name="setup"),
    path("admin/people/", include((people_urls, "admin.people"), namespace="admin")),
    path("admin/settings/", include(settings_urls)),
    path("admin/tasks/", include(admin_tasks_urls)),
    path("admin/templates/", include(template_urls)),
    path("admin/templates/todo/", include(to_do_urls)),
    path("admin/templates/hardware/", include(hardware_urls)),
    path("admin/templates/introductions/", include(intro_urls)),
    path("admin/templates/resources/", include(resource_urls)),
    path("admin/templates/badges/", include(badge_urls)),
    path("admin/templates/preboarding/", include(preboarding_urls)),
    path("admin/templates/appointments/", include(appointment_urls)),
    path("new_hire/", include(new_hire_urls)),
    path("admin/sequences/", include(sequences_urls)),
    path("api/slack/", include(slack_urls)),
    path("admin/integrations/", include(integrations_urls)),
]

# API
if settings.API_ACCESS:
    urlpatterns += [
        path("api/", include(public_api_urls)),
    ]

# DJANGO DEBUG BAR
if settings.DEBUG and not settings.RUNNING_TESTS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

back/users/models.py
import uuid
from datetime import datetime, timedelta

import pyotp
import pytz
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.db.models import CheckConstraint, Q
from django.template import Context, Template
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.functional import cached_property, lazy
from django.utils.translation import gettext_lazy as _
from django_q.tasks import async_task

from admin.appointments.models import Appointment
from admin.badges.models import Badge
from admin.hardware.models import Hardware
from admin.integrations.models import Integration
from admin.introductions.models import Introduction
from admin.preboarding.models import Preboarding
from admin.resources.models import CourseAnswer, Resource
from admin.sequences.models import Condition
from admin.to_do.models import ToDo
from misc.fernet_fields import EncryptedTextField
from misc.models import File
from organization.models import Notification
from slack_bot.utils import Slack, paragraph

from .utils import CompletedFormCheck


class Department(models.Model):
    """
    Department that has been attached to a user
    At the moment, only one department per user
    """

    name = models.TextField()

    def __str__(self):
        return "%s" % self.name


class CustomUserManager(BaseUserManager):
    def get_by_natural_key(self, email):
        # Make validation case sensitive
        return self.get(**{self.model.USERNAME_FIELD + "__iexact": email})


class ManagerSlackManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            role__in=[User.Role.MANAGER, User.Role.ADMIN]
        ) | super().get_queryset().exclude(slack_user_id="")


class OffboardingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(termination_date__isnull=False)


class ManagerManager(models.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(role__in=[User.Role.MANAGER, User.Role.ADMIN])
        )

    def with_slack(self):
        return self.get_queryset().exclude(slack_user_id="")


class NewHireManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(role=User.Role.NEWHIRE, termination_date__isnull=True)
        )

    def without_slack(self):
        return self.get_queryset().filter(slack_user_id="")

    def with_slack(self):
        return self.get_queryset().exclude(slack_user_id="")

    def starting_today(self):
        return (
            self.get_queryset().filter(start_day=datetime.now().date()).order_by("id")
        )

    def to_introduce(self):
        return self.get_queryset().filter(
            is_introduced_to_colleagues=False, start_day__gte=datetime.now().date()
        )


class AdminManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=get_user_model().Role.ADMIN)


class User(AbstractBaseUser):
    class Role(models.IntegerChoices):
        NEWHIRE = 0, _("New hire")
        ADMIN = 1, _("Administrator")
        MANAGER = 2, _("Manager")
        OTHER = 3, _("Other")

    first_name = models.CharField(verbose_name=_("First name"), max_length=200)
    last_name = models.CharField(verbose_name=_("Last name"), max_length=200)
    email = models.EmailField(verbose_name=_("Email"), max_length=200, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    birthday = models.DateField(verbose_name=_("Birthday"), default=None, null=True)
    position = models.CharField(
        verbose_name=_("Position"), max_length=300, default="", blank=True
    )
    phone = models.CharField(
        verbose_name=_("Phone"), max_length=300, default="", blank=True
    )
    slack_user_id = models.CharField(max_length=100, default="", blank=True)
    slack_channel_id = models.CharField(max_length=100, default="", blank=True)
    message = models.TextField(verbose_name=_("Message"), default="", blank=True)
    profile_image = models.ForeignKey(
        File, verbose_name=_("Profile image"), on_delete=models.CASCADE, null=True
    )
    linkedin = models.CharField(
        verbose_name=_("Linkedin"), default="", max_length=100, blank=True
    )
    facebook = models.CharField(
        verbose_name=_("Facebook"), default="", max_length=100, blank=True
    )
    twitter = models.CharField(
        verbose_name=_("Twitter"), default="", max_length=100, blank=True
    )
    timezone = models.CharField(
        verbose_name=_("Timezone"),
        default="",
        max_length=1000,
        choices=[(x, x) for x in pytz.common_timezones],
    )
    department = models.ForeignKey(
        Department, verbose_name=_("Department"), on_delete=models.SET_NULL, null=True
    )
    language = models.CharField(
        verbose_name=_("Language"),
        default="en",
        choices=settings.LANGUAGES,
        max_length=5,
    )
    role = models.IntegerField(
        verbose_name=_("Role"),
        choices=Role.choices,
        default=3,
        help_text=_(
            "An administrator has access to everything. A manager has only access to "
            "their new hires and their tasks."
        ),
    )
    is_active = models.BooleanField(default=True)
    is_introduced_to_colleagues = models.BooleanField(default=False)
    sent_preboarding_details = models.BooleanField(default=False)
    totp_secret = EncryptedTextField(blank=True)
    requires_otp = models.BooleanField(default=False)
    seen_updates = models.DateTimeField(auto_now_add=True)
    # new hire specific
    completed_tasks = models.IntegerField(default=0)
    total_tasks = models.IntegerField(default=0)
    buddy = models.ForeignKey(
        "self",
        verbose_name=_("Buddy"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="new_hire_buddy",
    )
    manager = models.ForeignKey(
        "self",
        verbose_name=_("Manager"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="new_hire_manager",
    )
    start_day = models.DateField(
        verbose_name=_("Start date"),
        null=True,
        blank=True,
        help_text=_("First working day"),
    )
    termination_date = models.DateField(
        verbose_name=_("Termination date"),
        null=True,
        blank=True,
        help_text=_("Last day of working"),
    )
    ran_integrations_condition = models.BooleanField(default=False)
    unique_url = models.CharField(max_length=250, unique=True)
    extra_fields = models.JSONField(default=dict)

    to_do = models.ManyToManyField(ToDo, through="ToDoUser", related_name="user_todos")
    introductions = models.ManyToManyField(
        Introduction, related_name="user_introductions"
    )
    resources = models.ManyToManyField(
        Resource, through="ResourceUser", related_name="user_resources"
    )
    appointments = models.ManyToManyField(Appointment, related_name="user_appointments")
    preboarding = models.ManyToManyField(
        Preboarding, through="PreboardingUser", related_name="user_preboardings"
    )
    badges = models.ManyToManyField(Badge, related_name="user_introductions")
    hardware = models.ManyToManyField(Hardware, related_name="user_hardware")
    integrations = models.ManyToManyField(
        "integrations.Integration",
        through="IntegrationUser",
        related_name="user_integrations",
    )

    # Conditions copied over from chosen sequences
    conditions = models.ManyToManyField(Condition)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()
    managers_and_admins = ManagerManager()
    managers_and_admins_or_slack_users = ManagerSlackManager()
    new_hires = NewHireManager()
    admins = AdminManager()
    offboarding = OffboardingManager()
    ordering = ("first_name",)

    class Meta:
        constraints = [
            CheckConstraint(
                check=~Q(unique_url=""),
                name="unique_url_not_empty",
            )
        ]

    @property
    def name(self):
        # used for search
        return self.full_name

    @cached_property
    def full_name(self):
        return f"{self.first_name} {self.last_name}".strip()

    @property
    def update_url(self):
        if self.role == User.Role.NEWHIRE:
            return reverse("people:new_hire", args=[self.id])
        else:
            return reverse("people:colleague", args=[self.id])

    def get_icon_template(self):
        return render_to_string("_user_icon.html")

    @cached_property
    def progress(self):
        if self.completed_tasks == 0 or self.total_tasks == 0:
            return 0
        return (self.completed_tasks / self.total_tasks) * 100

    @cached_property
    def initials(self):
        initial_characters = ""
        if len(self.first_name):
            initial_characters += self.first_name[0]
        if len(self.last_name):
            initial_characters += self.last_name[0]
        return initial_characters

    @property
    def is_offboarding(self):
        return self.termination_date is not None

    @property
    def has_slack_account(self):
        return self.slack_user_id != ""

    @cached_property
    def has_new_hire_notifications(self):
        # Notification bell badge on new hire pages
        last_notification = self.notification_receivers.latest("created")
        if last_notification is not None:
            return last_notification.created > self.seen_updates
        return False

    @cached_property
    def missing_extra_info(self):

back/admin/settings/templates/_personal_tabs.html
{% load i18n %}
<ul class="nav nav-tabs" data-bs-toggle="tabs">
    <li class="nav-item">
      <a href="{% url 'settings:personal-language' %}" class="nav-link {% if 'language' in request.path %} active{% endif %}">{% translate "Language" %}</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'settings:personal-otp' %}" class="nav-link {% if 'otp' in request.path %} active{% endif %}">{% translate "OTP" %}</a>
    </li>
</ul>

back/admin/settings/templates/integration-delete.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
<form method="POST">
  <div class="card-body">
    {% csrf_token %}
    {{ form|crispy }}
    <p>{% translate "Are you sure you want to remove this integration?" %}</p>
    <div class="form-footer">
      <button type="submit" class="btn btn-danger">{% translate "Disconnect integration" %}</button>
    </div>
  </div>
</form>
{% endblock %}

back/admin/settings/templates/org_general_update.html
{% extends 'settings_base.html' %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
  <div class="card-body">
    {% crispy form %}
  </div>
{% endblock %}

{% block extra_js %}
<script>
  // disable two options when not "make new user automatically"
  $("#id_auto_create_user").on('change', function() {
    if (this.checked == true){
      $("#div_id_create_new_hire_without_confirm").parent().parent().removeClass("d-none")
    } else {
      $("#div_id_create_new_hire_without_confirm").parent().parent().addClass("d-none")
    }
  })
  // disable two options when not "make new user automatically"
  $("#id_create_new_hire_without_confirm").on('change', function() {
    if (this.checked == false){
      $("#id_slack_confirm_person").parent().parent().removeClass("d-none")
    } else {
      $("#id_slack_confirm_person").parent().parent().addClass("d-none")
    }
  })
</script>
{% endblock %}

back/admin/settings/templates/org_welcome_message_update.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
<ul class="nav nav-tabs" data-bs-toggle="tabs">
  {% for language in languages %}
    <li class="nav-item">
      <a href="{% url 'settings:welcome-message' language.0 view.kwargs.type %}" class="nav-link {% if view.kwargs.language == language.0 %} active{% endif %}">{{ language.1 }}</a>
    </li>
  {% endfor %}
</ul>
<ul class="nav nav-tabs" data-bs-toggle="tabs">
  {% for type in types %}
    <li class="nav-item">
      <a href="{% url 'settings:welcome-message' view.kwargs.language type.0 %}" class="nav-link {% if view.kwargs.type == type.0 %} active{% endif %}">{{ type.1|title }}</a>
    </li>
  {% endfor %}
</ul>
<form method="POST">
  <div class="card-body">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-footer">
      <button type="submit" class="btn btn-primary">{% translate "Update" %}</button>
      <button hx-indicator="#spinner" hx-swap="none" hx-post="{% url 'settings:welcome-message-test-message' view.kwargs.language view.kwargs.type %}" class="btn">{% translate "Send test message" %}
        <span class="requesting alsodisplay" id="spinner">
          <div class="spinner-border spinner-border-sm text-muted" role="status"></div>
        </span>
      </button>
    </div>
  </div>
</form>
{% endblock %}

back/admin/settings/templates/personal_language_update.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
  {% include '_personal_tabs.html' %}
  <form method="POST">
    <div class="card-body">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="form-footer">
        <button type="submit" class="btn btn-primary">{% translate "Update" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

back/admin/settings/templates/personal_otp.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
  {% include '_personal_tabs.html' %}
  {% if not otp_url %}
    <div class="card-body">
      <p>{% translate "OTP has been enabled for your account" %}</p>
    {% if keys %}
      <p>{% translate "Please copy and save the keys below. These will only show once - you won't be able to see them again." %}</p>
      <p>{% translate "You will need these if you ever lose access to your 2FA app." %}</p>
      {% for key in keys %}
        <p><b>{{ key }}</b></p>
      {% endfor %}
    {% endif %}
    </div>
  {% else %}
    <form method="POST">
      {% csrf_token %}
      <div class="card-body">
        <p>{% translate "Please scan the code below with your 2FA app of your choice. We recommend andOTP or Aegis (but you can use Google Authenticator or Authy)." %}</p>
        <div class="mb-4" id="qrcode"></div>
        {{ form|crispy }}
        <div class="form-footer">
          <button type="submit" class="btn btn-primary">{% translate "Submit" %}</button>
        </div>
      </div>
    </form>
  {% endif %}
{% endblock %}
{% block js %}
<script src="{% static 'js/qrcode.min.js' %}"></script>
<script type="text/javascript">
  new QRCode(document.getElementById("qrcode"), "{{ otp_url }}");
</script>
{% endblock %}

back/admin/settings/templates/settings_admins.html
{% extends 'settings_base.html' %}
{% load i18n %}

{% block settings_content %}
  <div class="table-responsive">
  <table
		class="table table-vcenter table-nowrap">
    <thead>
      <tr>
        <th>{% translate "Name" %}</th>
        <th>{% translate "Role" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for admin in object_list %}
      <tr>
        <td>{% include "_table_user.html" with user=admin %}</td>
        <td>{{ admin.get_role_display }}</td>
        <td style="text-align: right">
          <a href="{% url 'settings:administrators-update' admin.id %}" class="btn btn-primary" {% if admin.id != request.user.id %}style="margin-top: -27px;"{% endif %}>
            {% translate "Change" %}
          </a>
          {% if admin.id != request.user.id %}
          <form method="post" action="{% url 'settings:administrators-delete' admin.id %}" class="mb-0" style="display:inline-block">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">
              {% translate "Delete" %}
            </button>
          </form>
          {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

back/admin/settings/templates/settings_admins_create.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
<form method="POST">
  <div class="card-body">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-footer">
      <button type="submit" class="btn btn-primary">{% translate "Add administrator" %}</button>
    </div>
  </div>
</form>
{% endblock %}

back/admin/settings/templates/settings_admins_update.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
<form method="POST">
  <div class="card-body">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-footer">
      <button type="submit" class="btn btn-primary">{% translate "Update administrator" %}</button>
    </div>
  </div>
</form>
{% endblock %}

back/admin/settings/templates/settings_base.html
{% extends 'admin_base.html' %}
{% load i18n %}

{% block actions %}{% endblock %}
{% block content %}
<div class="row">
  {% if user.is_admin %}
  <div class="col-2">
    <div class="card">
      <ul class="list-group">
        <a href="{% url 'settings:general' %}"><li class="list-group-item{% if 'general' in request.path %} active{% endif %}" aria-current="true">{% translate "General" %}</li></a>
        <a href="{% url 'settings:slack' %}"><li class="list-group-item{% if 'slack' in request.path %} active{% endif %}" aria-current="true">{% translate "Slack bot" %}</li></a>
        <a href="{% url 'settings:welcome-message' "en" 0 %}"><li class="list-group-item{% if 'welcome_message' in request.path %} active{% endif %}">{% translate "Welcome messages" %}</li></a>
        <a href="{% url 'settings:personal-language' %}"><li class="list-group-item{% if 'personal' in request.path %} active{% endif %}">{% translate "Personal" %}</li></a>
        <a href="{% url 'settings:integrations' %}"><li class="list-group-item{% if 'integrations' in request.path %} active{% endif %}">{% translate "Integrations" %}</li></a>
        <a href="{% url 'settings:administrators' %}"><li class="list-group-item{% if 'administrators' in request.path %} active{% endif %}">{% translate "Administrators" %}</li></a>
      </ul>
    </div>
  </div>
  {% endif %}
  <div class="col-{% if user.is_admin %}10{% else %}12{% endif %}">
    <div class="card">
      {% block settings_content %}
      {% endblock %}
    </div>
  </div>
</div>

{% endblock %}

back/admin/settings/templates/settings_google_login_setup.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}{% endblock %}
{% block settings_content %}
<form method="POST">
  <div class="card-body">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-footer">
      <button type="submit" class="btn btn-primary">{% translate "Update" %}</button>
    </div>
  </div>
</form>
{% endblock %}

back/admin/settings/templates/settings_integrations.html
{% extends 'settings_base.html' %}
{% load i18n %}

{% block settings_content %}
<div class="table-responsive">
  <table
		class="table table-vcenter table-nowrap">
    <thead>
      <tr>
        <th>{% translate "Official Integrations" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{% trans "Slack bot" %}</td>
        <td style="text-align: right">
          {% if slack_bot is not None %}
            <a href="{% url "settings:slack-account-update-channels" %}" class="btn btn-primary">
              {% trans "Update Slack channels list" %}
            </a>
            <a href="https://slack.com/oauth/v2/authorize?scope=im:history,users:read,chat:write,users:read.email,im:write,im:read,channels:read,groups:read&client_id={{ slack_bot.client_id }}&redirect_uri={{ base_url }}{% url 'integrations:slack' %}" class="btn btn-primary">
              Add to your Slack team
            </a>
            <a href="{% url 'integrations:delete' slack_bot.id %}" class="btn btn-danger">
              {% translate "Remove" %}
            </a>
          {% else %}
            <a href="{% url "settings:slack-bot" %}" class="btn btn-primary">
              {% translate "Enable" %}
            </a>
          {% endif %}
      </tr>
      <tr>
        <td>{% trans "Google login" %}</td>
        <td style="text-align: right">
          {% if google_login is not None %}
            <a href="{% url 'integrations:delete' google_login.id %}" class="btn btn-danger">
              {% translate "Remove" %}
            </a>
          {% else %}
            <a href="{% url "integrations:create-google" %}" class="btn btn-primary">
              {% translate "Enable" %}
            </a>
          {% endif %}
      </tr>
    </tbody>
  </table>
</div>
</div>
<div class="card mt-4">
<div class="table-responsive">
  <table
		class="table table-vcenter table-nowrap">
    <thead>
      <tr>
        <th>{% translate "Custom integrations" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for integration in custom_integrations %}
      <tr>
        <td>{{ integration.name }}</td>
        <td style="text-align: right">
          {% if integration.has_oauth and not integration.enabled_oauth %}
            <a href="{% url 'integrations:oauth' integration.id %}" class="btn btn-{% if integration.enabled_oauth %}success{% else %}primary{% endif %}">
              {% translate "OAuth" %}
            </a>
          {% endif %}
          {% if "initial_data_form" in integration.manifest %}
            <a href="{% url 'integrations:update-creds' integration.id %}" class="btn btn-primary">
              {% translate "Update credentials" %}
            </a>
          {% endif %}
          <a href="{% url 'integrations:update' integration.id %}" class="btn btn-primary">
            {% translate "Update manifest" %}
          </a>
          <a href="{% url 'integrations:delete' integration.id %}" class="btn btn-danger">
            {% translate "Remove" %}
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="2">{% trans "No custom integrations yet" %}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<a href="{% url 'integrations:builder' %}" class="btn btn-primary mt-2">Create new integration</a>
{% endblock %}

back/admin/settings/templates/token_create.html
{% extends 'settings_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}
  {% if object %}
  <a href="{% url 'integrations:builder' object.id %}" class="btn btn-primary">
      {% translate "Live edit and test" %}
  </a>
  {% endif %}
{% endblock %}
{% block settings_content %}
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">{% if button_text %}{{ button_text }}{% else %}{% translate "Submit" %}{% endif %}</button>
    </form>
    {% if object.has_oauth and not object.enabled_oauth %}
      {% translate "Redirect URL:" %} {{ request.scheme }}://{{ request.get_host }}{% url 'integrations:oauth-callback' object.id %}
    {% endif %}
  </div>
{% endblock %}