back/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("employees/", views.EmployeeView.as_view(), name="employees"),
    path("sequences/", views.SequenceView.as_view(), name="sequences"),
]

back/back/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import TemplateView

import user_auth
from admin.admin_tasks import urls as admin_tasks_urls
from admin.appointments import urls as appointment_urls
from admin.badges import urls as badge_urls
from admin.hardware import urls as hardware_urls
from admin.integrations import urls as integrations_urls
from admin.introductions import urls as intro_urls
from admin.people import urls as people_urls
from admin.preboarding import urls as preboarding_urls
from admin.resources import urls as resource_urls
from admin.sequences import urls as sequences_urls
from admin.settings import urls as settings_urls
from admin.templates import urls as template_urls
from admin.to_do import urls as to_do_urls
from api import urls as public_api_urls
from new_hire import urls as new_hire_urls
from organization import urls as org_urls
from organization import views as org_views
from slack_bot import urls as slack_urls
from user_auth import urls as auth_urls

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include(auth_urls)),
    path(
        "api/auth/google_login",
        user_auth.views.GoogleLoginView.as_view(),
        name="google_login",
    ),
    path("api/org/", include(org_urls)),
    path("setup/", org_views.InitialSetupView.as_view(), name="setup"),
    path("admin/people/", include((people_urls, "admin.people"), namespace="admin")),
    path("admin/settings/", include(settings_urls)),
    path("admin/tasks/", include(admin_tasks_urls)),
    path("admin/templates/", include(template_urls)),
    path("admin/templates/todo/", include(to_do_urls)),
    path("admin/templates/hardware/", include(hardware_urls)),
    path("admin/templates/introductions/", include(intro_urls)),
    path("admin/templates/resources/", include(resource_urls)),
    path("admin/templates/badges/", include(badge_urls)),
    path("admin/templates/preboarding/", include(preboarding_urls)),
    path("admin/templates/appointments/", include(appointment_urls)),
    path("new_hire/", include(new_hire_urls)),
    path("admin/sequences/", include(sequences_urls)),
    path("api/slack/", include(slack_urls)),
    path("admin/integrations/", include(integrations_urls)),
]

# API
if settings.API_ACCESS:
    urlpatterns += [
        path("api/", include(public_api_urls)),
    ]

# DJANGO DEBUG BAR
if settings.DEBUG and not settings.RUNNING_TESTS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

back/new_hire/urls.py
from django.urls import path

from new_hire import views

app_name = "new_hire"
urlpatterns = [
    path("todos/", views.NewHireDashboard.as_view(), name="todos"),
    path("resources/", views.ResourceListView.as_view(), name="resources"),
    path(
        "resources/search/",
        views.ResourceSearchView.as_view(),
        name="resources-search",
    ),
    path(
        "resources/<int:pk>/<int:chapter>/",
        views.ResourceDetailView.as_view(),
        name="resource-detail",
    ),
    path(
        "resources/form/<int:pk>/<int:chapter>/",
        views.CourseAnswerView.as_view(),
        name="question-form",
    ),
    path(
        "course/<int:pk>/", views.CourseNextStepView.as_view(), name="course-next-step"
    ),
    path("todos/<int:pk>/", views.ToDoDetailView.as_view(), name="to_do"),
    path("slackform/<int:pk>/", views.SlackToDoFormView.as_view(), name="slack_to_do"),
    path(
        "todos/<int:pk>/complete/",
        views.ToDoCompleteView.as_view(),
        name="to_do_complete",
    ),
    path(
        "<int:pk>/form/<slug:type>/",
        views.FormSubmitView.as_view(),
        name="form",
    ),
    path("colleagues/", views.ColleagueListView.as_view(), name="colleagues"),
    path(
        "colleagues/search/",
        views.ColleagueSearchView.as_view(),
        name="colleagues-search",
    ),
    path(
        "preboarding/",
        views.PreboardingShortURLRedirectView.as_view(),
        name="preboarding-url",
    ),
    path(
        "preboarding/<int:pk>/",
        views.PreboardingDetailView.as_view(),
        name="preboarding",
    ),
    path(
        "updates/",
        views.SeenUpdatesView.as_view(),
        name="seen-updates",
    ),
]

back/users/models.py
import uuid
from datetime import datetime, timedelta

import pyotp
import pytz
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.db.models import CheckConstraint, Q
from django.template import Context, Template
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.functional import cached_property, lazy
from django.utils.translation import gettext_lazy as _
from django_q.tasks import async_task

from admin.appointments.models import Appointment
from admin.badges.models import Badge
from admin.hardware.models import Hardware
from admin.integrations.models import Integration
from admin.introductions.models import Introduction
from admin.preboarding.models import Preboarding
from admin.resources.models import CourseAnswer, Resource
from admin.sequences.models import Condition
from admin.to_do.models import ToDo
from misc.fernet_fields import EncryptedTextField
from misc.models import File
from organization.models import Notification
from slack_bot.utils import Slack, paragraph

from .utils import CompletedFormCheck


class Department(models.Model):
    """
    Department that has been attached to a user
    At the moment, only one department per user
    """

    name = models.TextField()

    def __str__(self):
        return "%s" % self.name


class CustomUserManager(BaseUserManager):
    def get_by_natural_key(self, email):
        # Make validation case sensitive
        return self.get(**{self.model.USERNAME_FIELD + "__iexact": email})


class ManagerSlackManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            role__in=[User.Role.MANAGER, User.Role.ADMIN]
        ) | super().get_queryset().exclude(slack_user_id="")


class OffboardingManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(termination_date__isnull=False)


class ManagerManager(models.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(role__in=[User.Role.MANAGER, User.Role.ADMIN])
        )

    def with_slack(self):
        return self.get_queryset().exclude(slack_user_id="")


class NewHireManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(role=User.Role.NEWHIRE, termination_date__isnull=True)
        )

    def without_slack(self):
        return self.get_queryset().filter(slack_user_id="")

    def with_slack(self):
        return self.get_queryset().exclude(slack_user_id="")

    def starting_today(self):
        return (
            self.get_queryset().filter(start_day=datetime.now().date()).order_by("id")
        )

    def to_introduce(self):
        return self.get_queryset().filter(
            is_introduced_to_colleagues=False, start_day__gte=datetime.now().date()
        )


class AdminManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=get_user_model().Role.ADMIN)


class User(AbstractBaseUser):
    class Role(models.IntegerChoices):
        NEWHIRE = 0, _("New hire")
        ADMIN = 1, _("Administrator")
        MANAGER = 2, _("Manager")
        OTHER = 3, _("Other")

    first_name = models.CharField(verbose_name=_("First name"), max_length=200)
    last_name = models.CharField(verbose_name=_("Last name"), max_length=200)
    email = models.EmailField(verbose_name=_("Email"), max_length=200, unique=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    birthday = models.DateField(verbose_name=_("Birthday"), default=None, null=True)
    position = models.CharField(
        verbose_name=_("Position"), max_length=300, default="", blank=True
    )
    phone = models.CharField(
        verbose_name=_("Phone"), max_length=300, default="", blank=True
    )
    slack_user_id = models.CharField(max_length=100, default="", blank=True)
    slack_channel_id = models.CharField(max_length=100, default="", blank=True)
    message = models.TextField(verbose_name=_("Message"), default="", blank=True)
    profile_image = models.ForeignKey(
        File, verbose_name=_("Profile image"), on_delete=models.CASCADE, null=True
    )
    linkedin = models.CharField(
        verbose_name=_("Linkedin"), default="", max_length=100, blank=True
    )
    facebook = models.CharField(
        verbose_name=_("Facebook"), default="", max_length=100, blank=True
    )
    twitter = models.CharField(
        verbose_name=_("Twitter"), default="", max_length=100, blank=True
    )
    timezone = models.CharField(
        verbose_name=_("Timezone"),
        default="",
        max_length=1000,
        choices=[(x, x) for x in pytz.common_timezones],
    )
    department = models.ForeignKey(
        Department, verbose_name=_("Department"), on_delete=models.SET_NULL, null=True
    )
    language = models.CharField(
        verbose_name=_("Language"),
        default="en",
        choices=settings.LANGUAGES,
        max_length=5,
    )
    role = models.IntegerField(
        verbose_name=_("Role"),
        choices=Role.choices,
        default=3,
        help_text=_(
            "An administrator has access to everything. A manager has only access to "
            "their new hires and their tasks."
        ),
    )
    is_active = models.BooleanField(default=True)
    is_introduced_to_colleagues = models.BooleanField(default=False)
    sent_preboarding_details = models.BooleanField(default=False)
    totp_secret = EncryptedTextField(blank=True)
    requires_otp = models.BooleanField(default=False)
    seen_updates = models.DateTimeField(auto_now_add=True)
    # new hire specific
    completed_tasks = models.IntegerField(default=0)
    total_tasks = models.IntegerField(default=0)
    buddy = models.ForeignKey(
        "self",
        verbose_name=_("Buddy"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="new_hire_buddy",
    )
    manager = models.ForeignKey(
        "self",
        verbose_name=_("Manager"),
        on_delete=models.SET_NULL,
        null=True,
        related_name="new_hire_manager",
    )
    start_day = models.DateField(
        verbose_name=_("Start date"),
        null=True,
        blank=True,
        help_text=_("First working day"),
    )
    termination_date = models.DateField(
        verbose_name=_("Termination date"),
        null=True,
        blank=True,
        help_text=_("Last day of working"),
    )
    ran_integrations_condition = models.BooleanField(default=False)
    unique_url = models.CharField(max_length=250, unique=True)
    extra_fields = models.JSONField(default=dict)

    to_do = models.ManyToManyField(ToDo, through="ToDoUser", related_name="user_todos")
    introductions = models.ManyToManyField(
        Introduction, related_name="user_introductions"
    )
    resources = models.ManyToManyField(
        Resource, through="ResourceUser", related_name="user_resources"
    )
    appointments = models.ManyToManyField(Appointment, related_name="user_appointments")
    preboarding = models.ManyToManyField(
        Preboarding, through="PreboardingUser", related_name="user_preboardings"
    )
    badges = models.ManyToManyField(Badge, related_name="user_introductions")
    hardware = models.ManyToManyField(Hardware, related_name="user_hardware")
    integrations = models.ManyToManyField(
        "integrations.Integration",
        through="IntegrationUser",
        related_name="user_integrations",
    )

    # Conditions copied over from chosen sequences
    conditions = models.ManyToManyField(Condition)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()
    managers_and_admins = ManagerManager()
    managers_and_admins_or_slack_users = ManagerSlackManager()
    new_hires = NewHireManager()
    admins = AdminManager()
    offboarding = OffboardingManager()
    ordering = ("first_name",)

    class Meta:
        constraints = [
            CheckConstraint(
                check=~Q(unique_url=""),
                name="unique_url_not_empty",
            )
        ]

    @property
    def name(self):
        # used for search
        return self.full_name

    @cached_property
    def full_name(self):
        return f"{self.first_name} {self.last_name}".strip()

    @property
    def update_url(self):
        if self.role == User.Role.NEWHIRE:
            return reverse("people:new_hire", args=[self.id])
        else:
            return reverse("people:colleague", args=[self.id])

    def get_icon_template(self):
        return render_to_string("_user_icon.html")

    @cached_property
    def progress(self):
        if self.completed_tasks == 0 or self.total_tasks == 0:
            return 0
        return (self.completed_tasks / self.total_tasks) * 100

    @cached_property
    def initials(self):
        initial_characters = ""
        if len(self.first_name):
            initial_characters += self.first_name[0]
        if len(self.last_name):
            initial_characters += self.last_name[0]
        return initial_characters

    @property
    def is_offboarding(self):
        return self.termination_date is not None

    @property
    def has_slack_account(self):
        return self.slack_user_id != ""

    @cached_property
    def has_new_hire_notifications(self):
        # Notification bell badge on new hire pages
        last_notification = self.notification_receivers.latest("created")
        if last_notification is not None:
            return last_notification.created > self.seen_updates
        return False

    @cached_property
    def missing_extra_info(self):

back/new_hire/forms.py
from django import forms


class QuestionsForm(forms.Form):
    def __init__(self, items, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for idx, question in enumerate(items):
            self.fields[f"item-{idx}"] = forms.ChoiceField(
                choices=(
                    (option["id"], option["text"]) for option in question["items"]
                ),
                widget=forms.RadioSelect,
                label=question["content"],
            )

back/new_hire/templates/_chapter_recursive.html
<div style="margin-left:{{extra_margin}}px;">
{% if sub_chapter_item.children|length > 0 %}
  <div class="list-group-header sticky-top">{{ sub_chapter_item.name }}</div>
  {% for item in sub_chapter_item.children %}
    {% include '_chapter_recursive.html' with sub_chapter_item=item extra_margin=10 %}
  {% endfor %}
{% else %}
  {% if not object.course and sub_chapter_item.type == 2 %}
    {# not a course, so don't show #}
  {% elif object.course and sub_chapter_item.type == 2 and resource_user.completed_course %}
    {# a course, but completed, so don't show #}
  {% else %}
  <div class="list-group-item" style="border-left: 0px none; ">
    <div class="row align-items-center">
      <div class="col-auto">
        <span class="badge {% if view.kwargs.chapter == sub_chapter_item.id %}bg-primary{% endif %}"></span>
      </div>
      <div class="col text-truncate">
        {% if object.course and resource_user.step < sub_chapter_item.order and not resource_step.completed_course %}
          <s><span class="text-body d-block">{{ sub_chapter_item.name }}</span></s>
        {% else %}
          <a href="{% url 'new_hire:resource-detail' object.id sub_chapter_item.id %}" class="text-body d-block">{{ sub_chapter_item.name }}</a>
        {% endif %}
    </span>
      </div>
    </div>
  </div>
  {% endif %}
{% endif %}
</div>

back/new_hire/templates/_new_hire_to_do_item.html
{% load i18n %}
<tr>
  <td class="w-1">
    <input class="form-check-input" style="width: 1.5rem; height: 1.5rem" disabled type="checkbox" {% if to_do.completed %}checked=""{% endif %}>
  </td>
  <td class="td-truncate">
    <div class="text-truncate">
      {{ to_do.to_do.name }}
    </div>
  </td>
  <td class="text-end">
    <a href="{% url 'new_hire:to_do' to_do.id %}" class="btn btn-white">
      {% translate "View" %}
    </a>
  </td>
</tr>

back/new_hire/templates/new_hire_base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>{% translate "Employee onboarding" %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    <!-- CSS files -->
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <style>
      .btn-primary, .btn-outline-primary, .btn-ghost-primary, .btn-primary:hover, .btn-outline-primary:hover, .btn-ghost-primary:hover {
        --tblr-btn-color: {{ org.base_color_rgb }};
        --tblr-btn-color-darker: {{ org.base_color_rgb }};
      }
      a, a:hover, a:focus {
        color: rgb({{ org.base_color_rgb }})
      }
      .form-control:focus {
        color: inherit;
        background-color: #ffffff;
        border-color: rgb({{ org.base_color_rgb }});
        outline: 0;
        box-shadow: 0 0 0 0.25rem rgba({{ org.base_color_rgb }}, 0.25);
      }
      .page-item.active .page-link {
        background-color: rgb({{ org.base_color_rgb }});
        border-color: rgb({{ org.base_color_rgb }});
      }
      .page-link:hover {
        color: rgb({{ org.base_color_rgb }});
      }
      .form-check-input:checked, .bg-primary  {
        background-color: rgb({{ org.base_color_rgb }}) !important;
      }
    </style>
  </head>
  <body class="">
    <div class="wrapper">
      {% block header %}
      <header class="navbar navbar-expand-md navbar-dark navbar-overlap d-print-none" style="background-color: {{ org.base_color }}">
        <div class="container-xl">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if org.get_logo_url != "" %}
          <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href=".">
              <img src="{{ org.get_logo_url }}" class="navbar-brand-image" width="110" height="32">
            </a>
          </h1>
          {% endif %}
          <div class="navbar-nav flex-row order-md-last">
            <div class="nav-item dropdown d-none d-md-flex me-3" onclick="updateSeen()">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#navbar-templates" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" /><path d="M9 17v1a3 3 0 0 0 6 0v-1" /></svg>
                  {% if request.user.has_new_hire_notifications %}
                    <span class="badge bg-red"></span>
                  {% endif %}
                </a>
                <div class="dropdown-menu dropdown-menu-card dropdown-menu-right" style="width: 30rem;">
                  <div class="card d-flex flex-column">
                    <div class="card-body d-flex flex-column">
                      <h3 class="card-title">Notifications</h3>
                      <div class="list-group list-group-flush list-group-hoverable">
                        {% for notification in request.user.notification_receivers.all %}
                          {% if notification.public_to_new_hire %}
                          <div class="list-group-item">
                            <div class="row align-items-center">
                              {% if notification.has_not_seen %}
                                <div class="col-auto"><span class="badge bg-primary"></span></div>
                              {% endif %}
                              <div class="col text-truncate">
                                {% if notification.full_link == "" %}
                                <p class="text-reset d-block mb-0">{{ notification.get_notification_type_display }}:<br> <strong>{{ notification.extra_text }}</strong></p>
                                {% else %}
                                  <a href="{{ notification.full_link }}" class="text-reset d-block mb-0">{{ notification.get_notification_type_display }}: {{ notification.extra_text }}</a>
                                {% endif %}
                              </div>
                            </div>
                          </div>
                          {% endif %}
                        {% empty %}
                          No notifications yet
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="nav-item dropdown">
              <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu">
                {% include "_profile_image.html" %}
                <div class="d-none d-xl-block ps-2">
                  <div>{{ user.full_name }}</div>
                  <div class="mt-1 small text-muted">{{ user.get_role_display }}</div>
                </div>
              </a>
              <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                <a href="{% url 'logout' %}" class="dropdown-item">{% translate "Logout" %}</a>
              </div>
            </div>
          </div>
          <div class="collapse navbar-collapse" id="navbar-menu">
            <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
              {% if 'preboarding' not in request.path %}
              <ul class="navbar-nav">
                {% if request.user.role == 0 %}
                <li class="nav-item {% if 'todos' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:todos' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-circle-check" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <circle cx="12" cy="12" r="9"></circle>
                        <path d="M9 12l2 2l4 -4"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "To do items" %}
                    </span>
                  </a>
                </li>
                {% endif %}
                <li class="nav-item {% if 'resources' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:resources' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-folders" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M9 4h3l2 2h5a2 2 0 0 1 2 2v7a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2"></path>
                        <path d="M17 17v2a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2h2"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "Resources" %}
                    </span>
                  </a>
                </li>
                <li class="nav-item {% if 'colleagues' in request.path %}active{% endif %}">
                  <a class="nav-link" href="{% url 'new_hire:colleagues' %}">
                    <span class="nav-link-icon d-md-none d-lg-inline-block"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-users" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                        <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
                      </svg>
                    </span>
                    <span class="nav-link-title">
                      {% translate "Colleagues" %}
                    </span>
                  </a>
                </li>
              </ul>
              {% endif %}
            </div>
          </div>
        </div>
      </header>
      {% endblock %}
      <div class="page-wrapper">
        <div class="container-xl">
          <!-- Page title -->
          <div class="page-header text-white d-print-none">
            <div class="row align-items-center">
              <div class="col">
                <!-- Page pre-title -->
                <h2 class="page-title">{{ title }}</h2>
                <div class="page-pretitle">
                  {{ subtitle }}
                </div>
              </div>
              <!-- Page title actions -->
              {% for message in messages %}
              <div class="alert alert-success" style="color: black;">
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
              </div>
            {% endfor %}
              {% block actions %}
              {% endblock %}
            </div>
          </div>
        </div>
        <div class="page-body">
          <div class="container-xl">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>
      <div id="bin">
      </div>
    </div>
    <script src="{% static 'js/tabler.js' %}"></script>
    <script src="{% static 'js/htmx-1.7.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', function(event) {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
    <script>
      function updateSeen() {
          htmx.ajax("get", "{% url 'new_hire:seen-updates' %}", "#bin")
      }
    </script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

back/new_hire/templates/new_hire_resources.html
{% extends 'new_hire_base.html' %}
{% load i18n %}
{% load humanize %}

{% block actions %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{% translate "Resources" %}</h3>
      </div>
      <div class="list-group list-group-flush list-group-hoverable">
        {% for resource_user in object_list %}
          {% ifchanged resource_user.resource.category %}
            {% if resource_user.resource.category is not None %}
              <div class="list-group-header sticky-top">{{ resource_user.resource.category }}</div>
            {% endif %}
          {% endifchanged %}
        <div class="list-group-item" style="border-left: 0px none;">
          <div class="row align-items-center">
            <div class="col-auto">
              <span class="badge {% if resource_user.resource.course %} bg-primary {% endif %}"></span>
            </div>
            <div class="col text-truncate">
              <a href="{% url 'new_hire:resource-detail' resource_user.resource.id resource_user.resource.first_chapter_id %}" class="text-body d-block">{{ resource_user.resource.name }}</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{% translate "Search through resources" %}</h3>
      </div>
      <div class="card-body">
        <div class="input-icon float-right w-100">
          <input type="search"
                 class="form-control d-inline-block w-9 me-3"
                 placeholder="Search resources…"
                 name="search"
                 hx-get="{% url 'new_hire:resources-search' %}"
                 hx-trigger="keyup delay:500ms changed"
                 hx-target="#search-results"
                 hx-indicator="#spinner"
                 >
                 <span class="input-icon-addon requesting" id="spinner">
                   <div class="spinner-border spinner-border-sm text-muted" role="status"></div>
                 </span>
        </div>
        <div id="search-results"></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}