back/admin/introductions/urls.py
from django.urls import path

from . import views

app_name = "introductions"
urlpatterns = [
    path("", views.IntroductionListView.as_view(), name="list"),
    path("create/", views.IntroductionCreateView.as_view(), name="create"),
    path(
        "<int:pk>/edit/",
        views.IntroductionUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.IntroductionDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:pk>/preview/",
        views.IntroductionColleaguePreviewView.as_view(),
        name="preview",
    ),
]

back/admin/templates/urls.py
from django.urls import path

from . import views

app_name = "templates"
urlpatterns = [
    path(
        "duplicate/<slug:template_type>/<int:template_pk>/",
        views.TemplateDuplicateView.as_view(),
        name="duplicate",
    ),
    path(
        "duplicate_seq/<int:template_pk>/",
        views.SequenceDuplicateView.as_view(),
        name="duplicate_seq",
    ),
]

back/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("employees/", views.EmployeeView.as_view(), name="employees"),
    path("sequences/", views.SequenceView.as_view(), name="sequences"),
]

back/back/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import TemplateView

import user_auth
from admin.admin_tasks import urls as admin_tasks_urls
from admin.appointments import urls as appointment_urls
from admin.badges import urls as badge_urls
from admin.hardware import urls as hardware_urls
from admin.integrations import urls as integrations_urls
from admin.introductions import urls as intro_urls
from admin.people import urls as people_urls
from admin.preboarding import urls as preboarding_urls
from admin.resources import urls as resource_urls
from admin.sequences import urls as sequences_urls
from admin.settings import urls as settings_urls
from admin.templates import urls as template_urls
from admin.to_do import urls as to_do_urls
from api import urls as public_api_urls
from new_hire import urls as new_hire_urls
from organization import urls as org_urls
from organization import views as org_views
from slack_bot import urls as slack_urls
from user_auth import urls as auth_urls

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include(auth_urls)),
    path(
        "api/auth/google_login",
        user_auth.views.GoogleLoginView.as_view(),
        name="google_login",
    ),
    path("api/org/", include(org_urls)),
    path("setup/", org_views.InitialSetupView.as_view(), name="setup"),
    path("admin/people/", include((people_urls, "admin.people"), namespace="admin")),
    path("admin/settings/", include(settings_urls)),
    path("admin/tasks/", include(admin_tasks_urls)),
    path("admin/templates/", include(template_urls)),
    path("admin/templates/todo/", include(to_do_urls)),
    path("admin/templates/hardware/", include(hardware_urls)),
    path("admin/templates/introductions/", include(intro_urls)),
    path("admin/templates/resources/", include(resource_urls)),
    path("admin/templates/badges/", include(badge_urls)),
    path("admin/templates/preboarding/", include(preboarding_urls)),
    path("admin/templates/appointments/", include(appointment_urls)),
    path("new_hire/", include(new_hire_urls)),
    path("admin/sequences/", include(sequences_urls)),
    path("api/slack/", include(slack_urls)),
    path("admin/integrations/", include(integrations_urls)),
]

# API
if settings.API_ACCESS:
    urlpatterns += [
        path("api/", include(public_api_urls)),
    ]

# DJANGO DEBUG BAR
if settings.DEBUG and not settings.RUNNING_TESTS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

back/admin/introductions/models.py
from django.conf import settings
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from organization.models import BaseItem, Notification


class Introduction(BaseItem):
    intro_person = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Person to introduce"),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    @property
    def update_url(self):
        return reverse("introductions:update", args=[self.id])

    @property
    def delete_url(self):
        return reverse("introductions:delete", args=[self.id])

    def get_icon_template(self):
        return render_to_string("_intro_icon.html")

    @property
    def notification_add_type(self):
        return Notification.Type.ADDED_INTRODUCTION

back/admin/introductions/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout

from admin.templates.forms import MultiSelectField, TagModelForm

from .models import Introduction


class IntroductionForm(TagModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(
                Div(
                    Field("name"),
                    MultiSelectField("tags"),
                    Field("intro_person"),
                    css_class="col-12",
                ),
                css_class="row",
            ),
        )

    class Meta:
        model = Introduction
        exclude = ("template",)

back/admin/introductions/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from users.mixins import LoginRequiredMixin, ManagerPermMixin
from users.models import User

from .forms import IntroductionForm
from .models import Introduction


class IntroductionListView(LoginRequiredMixin, ManagerPermMixin, ListView):
    template_name = "templates.html"
    queryset = Introduction.templates.all().order_by("name")
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Introduction items")
        context["subtitle"] = _("templates")
        context["add_action"] = reverse_lazy("introductions:create")
        return context


class IntroductionCreateView(
    LoginRequiredMixin, ManagerPermMixin, SuccessMessageMixin, CreateView
):
    template_name = "intro_update.html"
    form_class = IntroductionForm
    success_url = reverse_lazy("introductions:list")
    success_message = _("Introduction item has been updated")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Create introduction item")
        context["subtitle"] = _("templates")
        return context


class IntroductionColleaguePreviewView(
    LoginRequiredMixin, ManagerPermMixin, DetailView
):
    template_name = "_colleague_intro.html"
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["intro_person"] = context["object"]
        return context


class IntroductionUpdateView(
    LoginRequiredMixin, ManagerPermMixin, SuccessMessageMixin, UpdateView
):
    template_name = "intro_update.html"
    form_class = IntroductionForm
    success_url = reverse_lazy("introductions:list")
    queryset = Introduction.templates.all()
    success_message = _("Introduction item has been updated")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Update introduction item")
        context["subtitle"] = _("templates")
        return context


class IntroductionDeleteView(
    LoginRequiredMixin, ManagerPermMixin, SuccessMessageMixin, DeleteView
):
    queryset = Introduction.objects.all()
    success_url = reverse_lazy("introductions:list")
    success_message = _("Introduction item has been removed")

back/admin/introductions/templates/_intro_icon.html
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
   <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
   <circle cx="12" cy="7" r="4"></circle>
   <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
</svg>

back/admin/introductions/templates/intro_update.html
{% extends 'admin_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}
  {% if object %}
    <form method="POST" action="{% url 'templates:duplicate' object.class_name object.id %}">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">
        {% translate "Duplicate" %}
      </button>
    </form>
    <form method="POST" action="{{ object.delete_url }}">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">
        {% translate "Delete" %}
      </button>
    </form>
  {% endif %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card">
      <form method="POST">
        <div class="card-body">
          <div class="row">
            <div class="col-6">
              {% crispy form %}
              <div class="form-footer">
                <button type="submit" class="btn btn-primary">{% if object %}{% translate "Update" %}{% else %}{% translate "Create" %}{% endif %}</button>
              </div>
            </div>
            <div class="col-6">
              <h3>{% translate "Preview" %}</h3>
              <div class="update-intro">
                {% include "_colleague_intro.html" with intro_person=object.intro_person  %}
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
$("select#id_intro_person").on('change', function() {
    const userId = $(this).val()
    htmx.ajax('GET', `/templates/introductions/${userId}/preview/`, `.update-intro`)
})
</script>

{% endblock %}