back/admin/admin_tasks/urls.py
from django.urls import path

from . import views

app_name = "admin_tasks"
urlpatterns = [
    path("create/", views.AdminTasksCreateView.as_view(), name="create"),
    path("mine/", views.MyAdminTasksListView.as_view(), name="mine"),
    path("all/", views.AllAdminTasksListView.as_view(), name="all"),
    path("<int:pk>/", views.AdminTasksUpdateView.as_view(), name="detail"),
    path(
        "<int:pk>/completed/", views.AdminTaskCompleteView.as_view(), name="completed"
    ),
    path(
        "<int:pk>/comment/", views.AdminTasksCommentCreateView.as_view(), name="comment"
    ),
]

back/api/urls.py
from django.urls import path

from . import views

app_name = "api"
urlpatterns = [
    path("users/", views.UserView.as_view(), name="users"),
    path("employees/", views.EmployeeView.as_view(), name="employees"),
    path("sequences/", views.SequenceView.as_view(), name="sequences"),
]

back/back/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import TemplateView

import user_auth
from admin.admin_tasks import urls as admin_tasks_urls
from admin.appointments import urls as appointment_urls
from admin.badges import urls as badge_urls
from admin.hardware import urls as hardware_urls
from admin.integrations import urls as integrations_urls
from admin.introductions import urls as intro_urls
from admin.people import urls as people_urls
from admin.preboarding import urls as preboarding_urls
from admin.resources import urls as resource_urls
from admin.sequences import urls as sequences_urls
from admin.settings import urls as settings_urls
from admin.templates import urls as template_urls
from admin.to_do import urls as to_do_urls
from api import urls as public_api_urls
from new_hire import urls as new_hire_urls
from organization import urls as org_urls
from organization import views as org_views
from slack_bot import urls as slack_urls
from user_auth import urls as auth_urls

urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("", include(auth_urls)),
    path(
        "api/auth/google_login",
        user_auth.views.GoogleLoginView.as_view(),
        name="google_login",
    ),
    path("api/org/", include(org_urls)),
    path("setup/", org_views.InitialSetupView.as_view(), name="setup"),
    path("admin/people/", include((people_urls, "admin.people"), namespace="admin")),
    path("admin/settings/", include(settings_urls)),
    path("admin/tasks/", include(admin_tasks_urls)),
    path("admin/templates/", include(template_urls)),
    path("admin/templates/todo/", include(to_do_urls)),
    path("admin/templates/hardware/", include(hardware_urls)),
    path("admin/templates/introductions/", include(intro_urls)),
    path("admin/templates/resources/", include(resource_urls)),
    path("admin/templates/badges/", include(badge_urls)),
    path("admin/templates/preboarding/", include(preboarding_urls)),
    path("admin/templates/appointments/", include(appointment_urls)),
    path("new_hire/", include(new_hire_urls)),
    path("admin/sequences/", include(sequences_urls)),
    path("api/slack/", include(slack_urls)),
    path("admin/integrations/", include(integrations_urls)),
]

# API
if settings.API_ACCESS:
    urlpatterns += [
        path("api/", include(public_api_urls)),
    ]

# DJANGO DEBUG BAR
if settings.DEBUG and not settings.RUNNING_TESTS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

back/admin/admin_tasks/models.py
from django.conf import settings
from django.db import models
from django.template.loader import render_to_string
from django.utils.translation import gettext as _

from organization.models import Notification
from slack_bot.utils import Slack, actions, button, paragraph

from .emails import (
    send_email_new_assigned_admin,
    send_email_new_comment,
    send_email_notification_to_external_person,
)


class AminTaskManager(models.Manager):
    def create_admin_task(
        self,
        new_hire,
        assigned_to,
        name,
        option=0,
        slack_user=None,
        email="",
        date=None,
        priority=2,
        pending_admin_task=None,
        hardware=None,
        manual_integration=None,
        comment="-",
        send_notification=True,
    ):
        admin_task = AdminTask.objects.create(
            new_hire=new_hire,
            assigned_to=assigned_to,
            name=name,
            option=option,
            slack_user=slack_user,
            email=email,
            date=date,
            priority=priority,
            based_on=pending_admin_task,
            hardware=hardware,
            manual_integration=manual_integration,
        )
        AdminTaskComment.objects.create(
            content=comment,
            comment_by=admin_task.assigned_to,
            admin_task=admin_task,
        )
        if send_notification:
            admin_task.send_notification_new_assigned()

        admin_task.send_notification_third_party()

        Notification.objects.create(
            notification_type=Notification.Type.ADDED_ADMIN_TASK,
            extra_text=name,
            created_for=admin_task.assigned_to,
        )


class AdminTask(models.Model):
    class Priority(models.IntegerChoices):
        EMAIL = 1, _("Low")
        MEDIUM = 2, _("Medium")
        HIGH = 3, _("High")

    class Notification(models.IntegerChoices):
        NO = 0, _("No")
        EMAIL = 1, _("Email")
        SLACK = 2, _("Slack")

    new_hire = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("New hire"),
        on_delete=models.CASCADE,
        related_name="new_hire_tasks",
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Assigned to"),
        on_delete=models.CASCADE,
        related_name="owner",
        blank=True,
        null=True,
    )
    name = models.CharField(verbose_name=_("Name"), max_length=500)
    option = models.IntegerField(
        verbose_name=_("Send email or text to extra user?"),
        choices=Notification.choices,
    )
    slack_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Slack user"),
        on_delete=models.SET_NULL,
        related_name="slack_user",
        blank=True,
        null=True,
    )
    email = models.EmailField(
        verbose_name=_("Email"), max_length=12500, default="", blank=True
    )
    completed = models.BooleanField(verbose_name=_("Completed"), default=False)
    date = models.DateField(verbose_name=_("Date"), blank=True, null=True)
    priority = models.IntegerField(
        verbose_name=_("Priority"), choices=Priority.choices, default=Priority.MEDIUM
    )
    based_on = models.ForeignKey(
        "sequences.PendingAdminTask",
        null=True,
        on_delete=models.SET_NULL,
        help_text=_("If generated through a sequence, then this will be filled"),
    )
    manual_integration = models.ForeignKey(
        "integrations.Integration",
        null=True,
        on_delete=models.SET_NULL,
        help_text=_("Only set if generated based on a manual integration."),
    )
    hardware = models.ForeignKey(
        "hardware.Hardware",
        null=True,
        on_delete=models.SET_NULL,
        help_text=_("Only set if generated based on hardware."),
    )

    objects = AminTaskManager()

    def get_icon_template(self):
        return render_to_string("_admin_task_icon.html")

    def send_notification_third_party(self):
        if self.assigned_to is None:
            # Only happens when a sequence adds this with "manager" or "buddy" is
            # choosen option
            return
        if self.option == AdminTask.Notification.EMAIL:
            send_email_notification_to_external_person(self)
        elif self.option == AdminTask.Notification.SLACK:
            blocks = [
                paragraph(
                    _(
                        "%(name_assigned_to)s needs your help with this task:\n*"
                        "%(task_name)s*\n_%(comment)s_"
                    )
                    % {
                        "name_assigned_to": self.assigned_to.full_name,
                        "task_name": self.name,
                        "comment": self.comment.last().content,
                    }
                ),
                actions(
                    [
                        button(
                            text=_("I have completed this"),
                            style="primary",
                            value=str(self.pk),
                            action_id="admin_task:complete",
                        )
                    ]
                ),
            ]
            Slack().send_message(blocks, self.slack_user.slack_user_id)

    def send_notification_new_assigned(self):
        if self.assigned_to is None:
            # Only happens when a sequence adds this with "manager" or "buddy" is
            # choosen option
            return
        if self.assigned_to.has_slack_account:
            comment = ""
            if self.comment.all().exists():
                comment = _("_%(comment)s_\n by _%(name)s_") % {
                    "comment": self.comment.last().content,
                    "name": self.comment.last().comment_by.full_name,
                }

            text = _("You have just been assigned to *%(title)s* for *%(name)s*\n") % {
                "title": self.name,
                "name": self.new_hire.full_name,
            }
            text += comment
            blocks = [
                paragraph(text),
                actions(
                    [
                        button(
                            text=_("I have completed this"),
                            style="primary",
                            value=str(self.pk),
                            action_id="admin_task:complete",
                        )
                    ]
                ),
            ]
            Slack().send_message(
                blocks=blocks,
                channel=self.assigned_to.slack_user_id,
                text=_("New assigned task!"),
            )
        else:
            send_email_new_assigned_admin(self)

    def mark_completed(self):
        from admin.sequences.tasks import process_condition

        self.completed = True
        self.save()

        # Check if we need to register the manual integration
        if self.manual_integration is not None:
            self.manual_integration.register_manual_integration_run(self.new_hire)

        # Check if we need to register hardware
        if self.hardware is not None:
            self.hardware.remove_or_add_to_user(self.new_hire)

        # Get conditions with this to do item as (part of the) condition
        conditions = self.new_hire.conditions.filter(
            condition_admin_tasks=self.based_on
        )

        for condition in conditions:
            condition_admin_tasks_id = condition.condition_admin_tasks.values_list(
                "id", flat=True
            )

            # Check if all admin to do items have been added to new hire and are
            # completed. If not, then we know it should not be triggered yet
            completed_tasks = AdminTask.objects.filter(
                based_on_id__in=condition_admin_tasks_id,
                new_hire=self.new_hire,
                completed=True,
            )

            # If the amount matches, then we should process it
            if completed_tasks.count() == len(condition_admin_tasks_id):
                # Send notification only if user has a slack account
                process_condition(
                    condition.id, self.new_hire.id, self.new_hire.has_slack_account
                )

    class Meta:
        ordering = ["completed", "date"]


class AdminTaskComment(models.Model):
    admin_task = models.ForeignKey(
        "AdminTask", on_delete=models.CASCADE, related_name="comment"
    )
    content = models.CharField(max_length=12500)
    date = models.DateTimeField(auto_now_add=True)
    comment_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-date"]

    def send_notification_new_message(self):
        if self.admin_task.assigned_to != self.comment_by:
            if self.admin_task.assigned_to.has_slack_account:
                blocks = [
                    paragraph(
                        _(
                            "%(name)s added a message to your task:\n*"
                            "%(task_title)s*\n_%(comment)s_"
                        )
                        % {
                            "name": self.comment_by.full_name,
                            "task_title": self.admin_task.name,
                            "comment": self.content,
                        }
                    ),
                    actions(
                        [
                            button(
                                text=_("I have completed this"),
                                style="primary",
                                value=str(self.pk),
                                action_id="admin_task:complete",
                            )
                        ]
                    ),
                ]
                Slack().send_message(blocks, self.admin_task.assigned_to.slack_user_id)
            else:
                send_email_new_comment(self)

back/admin/admin_tasks/forms.py
from django import forms

from users.models import User

from .models import AdminTask, AdminTaskComment


class AdminTaskCommentForm(forms.ModelForm):
    class Meta:
        model = AdminTaskComment
        fields = [
            "content",
        ]


class AdminTaskUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, "instance", None)
        if instance is not None and instance.completed:
            for field in self.fields:
                self.fields[field].widget.attrs["disabled"] = True

    class Meta:
        model = AdminTask
        fields = ["name", "assigned_to", "date", "priority"]


class AdminTaskCreateForm(forms.ModelForm):
    comment = forms.CharField(max_length=12500)
    new_hire = forms.ModelChoiceField(queryset=User.new_hires.all())
    assigned_to = forms.ModelChoiceField(queryset=User.admins.all())
    slack_user = forms.ModelChoiceField(queryset=User.managers_and_admins.with_slack())
    date = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"type": "date"}, format=("%Y-%m-%d")),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["option"].initial = 0
        self.fields["slack_user"].required = False

    class Meta:
        model = AdminTask
        fields = [
            "name",
            "new_hire",
            "assigned_to",
            "date",
            "priority",
            "comment",
            "option",
            "slack_user",
            "email",
        ]

back/admin/admin_tasks/templates/_admin_task_icon.html
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-list-check" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
  <path d="M3.5 5.5l1.5 1.5l2.5 -2.5"></path>
  <path d="M3.5 11.5l1.5 1.5l2.5 -2.5"></path>
  <path d="M3.5 17.5l1.5 1.5l2.5 -2.5"></path>
  <line x1="11" y1="6" x2="20" y2="6"></line>
  <line x1="11" y1="12" x2="20" y2="12"></line>
  <line x1="11" y1="18" x2="20" y2="18"></line>
</svg>

back/admin/admin_tasks/templates/admin_tasks_all.html
{% extends 'admin_base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title">{% translate "All tasks" %}</h3>
  </div>
  <table class="table table-responsive table-vcenter text-nowrap">
    <thead>
      <tr>
        <th>{% translate "For new hire" %}</th>
        <th>{% translate "Task" %}</th>
        <th>{% translate "Due in" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in object_list %}
      <tr>
        <td>
          {% include "_table_user.html" with user=task.new_hire %}
        </td>
        <td>
          <div class="text-truncate">
            {{ task.name }}
          </div>
        </td>
        <td>{% if task.date|naturaltime is not None %}{{ task.date|naturaltime }}{% else %}{% translate "No deadline set" %}{%endif %}</td>
        <td class="text-end">
          {% if task.completed %}<button class="btn btn-success" disabled>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-check" style="margin-right: 0" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
               <path d="M5 12l5 5l10 -10"></path>
            </svg>
          </button>{% endif %}
          <a href="{% url 'admin_tasks:detail' task.id %}" class="btn btn-white">
            View
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">
          {% translate "There are no open items" %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "_paginator.html" %}
</div>
{% endblock %}

back/admin/admin_tasks/templates/admin_tasks_create.html
{% extends 'admin_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <form class="mt-3" method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="form-footer">
            <button type="submit" class="btn btn-primary">{% translate "Create" %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
$(document).ready(function () {
  $("#div_id_slack_user").addClass("d-none")
  $("#div_id_email").addClass("d-none")
})

$("select#id_option").on('change', function() {
  // Change things to fill in when condition_type changes
  if ($(this).val() == 0){
    $("#div_id_slack_user").addClass("d-none")
    $("#div_id_email").addClass("d-none")
  } else if ($(this).val() == 2){
    $("#div_id_slack_user").removeClass("d-none")
    $("#div_id_email").addClass("d-none")
  } else {
    $("#div_id_slack_user").addClass("d-none")
    $("#div_id_email").removeClass("d-none")
  }
})
</script>
{% endblock %}

back/admin/admin_tasks/templates/admin_tasks_detail.html
{% extends 'admin_base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block actions %}
{% if not object.completed %}
  <form method="post" action="{% url 'admin_tasks:completed' object.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
      {% translate "Complete" %}
    </button>
  </form>
{% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        {% include "_table_user.html" with user=object.new_hire %}
        <form class="mt-3" method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          {% if not object.completed %}
          <div class="form-footer">
            <button type="submit" class="btn btn-primary">{% translate "Update" %}</button>
          </div>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
  <div class="col-8">
    {% if not object.completed %}
    <div class="card mb-3">
      <div class="card-header">
        <h3 class="card-title">{% translate "Add comment" %}</h3>
      </div>
      <div class="card-body">
        <form method="POST" action="{% url 'admin_tasks:comment' object.id %}">
          {% csrf_token %}
          {{ comment_form|crispy }}
          <div class="form-footer">
            <button type="submit" class="btn btn-primary">{% translate "Submit" %}</button>
          </div>
        </form>
      </div>
    </div>
    {% endif %}
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">{% translate "Comments" %}</h3>
      </div>
      <div class="card-body">
        {% if object.comment.all|length %}
        <ul class="mt-3 list list-timeline">
          {% for comment in object.comment.all %}
          <li>
            <div class="list-timeline-icon {% if comment.comment_by == request.user %}bg-primary{% else %}bg-secondary{% endif %}"></div>
            <div class="list-timeline-content">
              <p class="mb-0 text-muted">{{ comment.content }}</p>
              <p><span class="list-timeline-title">{{ comment.comment_by }}</span> - {{ comment.date }}</p>
            </div>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <p class="mt-3">{% translate "There are no comments yet" %}</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

back/admin/admin_tasks/templates/admin_tasks_yours.html
{% extends 'admin_base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title">{% translate "Your tasks" %}</h3>
  </div>
  <table class="table table-responsive table-vcenter text-nowrap">
    <thead>
      <tr>
        <th>{% translate "For new hire" %}</th>
        <th>{% translate "Task" %}</th>
        <th>{% translate "Due in" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in object_list %}
      <tr>
        <td>
          {% include "_table_user.html" with user=task.new_hire %}
        </td>
        <td>
          <div class="text-truncate">
            {{ task.name }}
          </div>
        </td>
        <td>{% if task.date|naturaltime is not None %}{{ task.date|naturaltime }}{% else %}{% translate "No deadline set" %}{%endif %}</td>
        <td class="text-end">
          {% if task.completed %}<button class="btn btn-success" disabled>
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-check" style="margin-right: 0" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
               <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
               <path d="M5 12l5 5l10 -10"></path>
            </svg>
          </button>{% endif %}
          <a href="{% url 'admin_tasks:detail' task.id %}" class="btn btn-white">
            View
          </a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">
          {% translate " There are no open items" %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "_paginator.html" %}
</div>
{% endblock %}